version: '3.8'

services:
  frontend:
    build:
      context: ./frontend/src
      dockerfile: Dockerfile
    ports:
      - "7777:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dappsteros
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
