apiVersion: apps/v1
kind: Deployment
metadata:
  name: dappsteros-dashboard-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: dappsteros-dashboard-frontend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 3000
        env:
        - name: PORT
          value: "8080"
        - name: API_ADDR
          value: dappsteros-dashboard-backend
        - name: API_PORT
          value: "8000"
