import type { Metadata } from "next";
import "../../globals.css";
import NoLayout from "@/components/NoLayout";

export const metadata: Metadata = {
  title: "DappsterOS",
  description: "Generated by AlphaCoX",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <NoLayout>{children}</NoLayout>;
}
